import React from 'react'
import ReactDOM from 'react-dom'
import { API_KEY } from './API_KEY'
import YTSearch from 'youtube-api-search'

import SearchBar from './components/search_bar'

// Class-based component
class App extends Component {
	constructor(props) {
		super(props);

		this.state = { videos: [] };

		YTSearch({key: API_KEY, term: 'surfboards'}, function (data) {
			this.setState({ videos: data })
		});
	}

	render() {
		return (
			<div>
				<SearchBar/>
			</div>
		)
	}
}

// Take the HTML generated by the component and put it on the page DOM
// reactDOM library modifies the DOM
ReactDOM.render(<App />, document.querySelector('.container'));