import React, { Component } from 'react'
import ReactDOM from 'react-dom'
import { API_KEY } from './API_KEY'
import YTSearch from 'youtube-api-search'
import SearchBar from './components/search_bar'
import VideoList from './components/video_list'
import VideoDetail from './components/video_detail'

// Class-based component
class App extends Component {
	constructor(props) {
		super(props);

		this.state = { videos: [] };

		YTSearch({key: API_KEY, term: 'surfboards'}, (videos) => {
			this.setState({ videos })
		});
	}

	render() {
		return (
			<div>
				<SearchBar/>
				<VideoDetail video={this.state.videos[0]}/>
				<VideoList videos={this.state.videos}/>
			</div>
		)
	}
}

// Take the HTML generated by the component and put it on the page DOM
// reactDOM library modifies the DOM
ReactDOM.render(<App />, document.querySelector('.container'));